# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
#jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
#twitter:
#  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
#author: DavidDarnes # jekyll-seo-tag > default author
#social: # jekyll-seo-tag > social overrides
#  name: David Darnes # jekyll-seo-tag > real name
#  links:  # jekyll-seo-tag > social aliases (sameAs)
#    - https://twitter.com/DavidDarnes
#    - https://www.facebook.com/daviddarnes
#    - https://www.linkedin.com/in/daviddarnes
#    - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: "Журнал по полевой лингвистике" # Needed for Siteleaf
    output: true
    description: "Мы хотим узнать, что вы делаете в экспедиции! Журнал выходит 1 раз в год. Мы публикуем работы двух жанров: экспедиционные обзоры и лингвистические заметки." # The post list page content
    feature_image: "/assets/header_journal.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: ru-RU # Set the site language
title: "ОПЛинг" # Site name or title, also used in jekyll-seo-tag
logo: "https://avatars.githubusercontent.com/u/88092974?v=4" # Site logo, also used in jekyll-seo-tag
description: "Общество полевых лингвистов" # Site description and default description, also used in jekyll-seo-tag
url: "?????????????????????" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/opling/???????????????????"
email: "oplingvi@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@32px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  512: '/assets/logos/logo@512px.png'

# 9. Site navigation
navigation_header:
- title: Главная
  url: /
- title: Встречи
  url: /events/
- title: Журнал
  url: /blog/
- title: Авторам
  url: /info_for_authors/
- title: Навигация по тэгам
  url: /categories/
- title: Поиск
  url: /search/
- title: Члены ОПЛинга
  url: /members/

navigation_footer:
- title: Created by Konstantin Filatov, template by David Darnes

#social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
#  Twitter: https://twitter.com/DavidDarnes
#  LinkedIn: https://www.linkedin.com/in/daviddarnes
#  GitHub: https://github.com/daviddarnes
#  link: https://darn.es
#  RSS: /feed.xml

#sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
#  Twitter: "#0d94e7"
#  facebook: "#3B5998"

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap

# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
staticman_url: https://staticman-oplingio.herokuapp.com/v2/entry/opling/opling.github.io/master/comments

reCaptcha:
  siteKey: 6LdrxkgcAAAAAHaK_OpHbqEUYK70bumdmZTyZhzM
  secret: g3FCzlk09vxubTz57c8SSswNUPZ5WatxU3mPbIqiEeQptFX7X2mspk6eJILHugsWfHFLJ/OoUqLvB+fkMy0QnW8Nt1wGKwjQcwauIrTBZ5BVIZb2nmmcerWFamw+IIy4x7OGNyELBpDmUIWa+cZTrM+4ZQtlaqz085OPz6jaweRE/PsWqA1w+EZ6ccEEeqwtVCQlzoark8Ce98Hc6ed+SoaSbBHfLbguSc9yD34DyekYStW9XY0PO8Zii1hn0weBmyKEz+75yC29cCrqaLevCbvoBQWLTv16u/CrblC8P3MJ7Vv0sQOPXVlo13VR5tUZPa0MYt965WRi4NfvKwIX4Ia1AU9FrX4dGKA7J5uzDuwMGyG/BKYQsctNKH36dOLyfW/nBCaVnSce8hhBrcoVqVqBn6peIkV7ddGZMn2gIdxwHmSFnlhVj5RNVKmntAzWv7yHT2hNsA5I/36x0Zf76K35FbeoeHyrs6AsjbkViGMGbO9pK9AlTI5l5iSIeE4Kl6KLGIHQdH9uuQQr3MpTfBdcth/oLYFQ/D6vV79pjI/xDCdnuXwr3x31sywZshORvIz/rXHEStv4YKh1sfM1AmNNvGpkwwa+JsjsuE4Mn6tZY/IT+W+ir/xjR+TQ764KDMoj1tiu6CDOL9Q9rAzzImqIR1A6lbA0oi6JslQcAYI=